export const COURSES = [
  // 300 Level
  { code: "BSCS-301", name: "Introduction to Computer Science - I" },
  { code: "BSCS-302", name: "Introduction to Computer Science - II" },
  { code: "BSCS-303", name: "Mathematics - I (Calculus)" },
  { code: "BSCS-304", name: "Mathematics - II (Differential Equations)" },
  { code: "BSCS-305", name: "Statistics and Data Analysis" },
  { code: "BSCS-306", name: "Probability and Statistical Methods" },
  { code: "BSCS-307", name: "Physics - I (General Physics)" },
  { code: "BSCS-308", name: "Physics - II (Electricity and Magnetism)" },
  { code: "BSCS-309", name: "English - I" },
  { code: "BSCS-310", name: "English - II" },
  { code: "BSCS-311", name: "Islamic Learning & Pakistan Studies" },
  { code: "BSCS-312", name: "Urdu" },
  // 400 Level
  { code: "BSCS-401", name: "Digital Computer Design Fundamentals" },
  { code: "BSCS-402", name: "Data Structure" },
  { code: "BSCS-403", name: "Assembly Language Programming" },
  { code: "BSCS-404", name: "System Design with Microprocessor" },
  { code: "BSCS-405", name: "Mathematics - III (Linear Algebra and Analytical Geometry)" },
  { code: "BSCS-406", name: "Mathematics (Numerical Analysis and Computing)" },
  { code: "BSCS-407", name: "Communication Skills and Report Writing" },
  { code: "BSCS-408", name: "Object Oriented Programming" },
  { code: "BSCS-409", name: "Materials, Semiconductors and Devices" },
  { code: "BSCS-410", name: "Electronics" },
  { code: "BSCS-411", name: "Discrete Mathematics" },
  { code: "BSCS-412", name: "Software Engineering and Project Management" },
  // 500 Level
  { code: "BSCS-501", name: "Theory of Computer Science" },
  { code: "BSCS-502", name: "Concepts of Operating Systems" },
  { code: "BSCS-503", name: "Data Communication and Networking - I" },
  { code: "BSCS-504", name: "Compiler Construction - I" },
  { code: "BSCS-505", name: "Stochastic Process and Inference" },
  { code: "BSCS-506", name: "Modeling and Simulation" },
  { code: "BSCS-507", name: "Operations Research - I" },
  { code: "BSCS-508", name: "Operations Research - II" },
  { code: "BSCS-509", name: "Database Systems" },
  { code: "BSCS-510", name: "Microcomputer Design and Interfacing - I" },
  { code: "BSCS-511", name: "Computer Organization and Architecture" },
  { code: "BSCS-512", name: "Data Communication and Networking - II" },
  { code: "BSCS-513", name: "Advanced Numerical Computing" },
  { code: "BSCS-514", name: "Computer Graphics" },
  { code: "BSCS-515", name: "Artificial Intelligence" },
  { code: "BSCS-517", name: "System Analysis & Design" },
  { code: "BSCS-519", name: "Business Programming Languages" },
  { code: "BSCS-520", name: "Advanced Software Engineering" },
  { code: "BSCS-522", name: "Expert Systems" },
  // 600 Level
  { code: "BSCS-601", name: "Theory of Operating Systems" },
  { code: "BSCS-602", name: "Operating Systems Case Study" },
  { code: "BSCS-603", name: "Compiler Construction - II" },
  { code: "BSCS-604", name: "Natural Language Processing" },
  { code: "BSCS-605", name: "Advanced Computer Graphics" },
  { code: "BSCS-606", name: "Distributed Database Systems" },
  { code: "BSCS-607", name: "Financial Accounting" },
  { code: "BSCS-609", name: "Microcomputers Design and Interfacing - II" },
  { code: "BSCS-610", name: "Design and Analysis of Algorithms" },
  { code: "BSCS-611", name: "Parallel Computing" },
  { code: "BSCS-612", name: "Financial Management" },
  { code: "BSCS-613", name: "Management Information Systems" },
  { code: "BSCS-616", name: "Multimedia Systems" },
  { code: "BSCS-618", name: "Computational Linear Algebra" },
  { code: "BSCS-619", name: "Thesis - I" },
  { code: "BSCS-620", name: "Thesis - II" },
  { code: "BSCS-621", name: "Topics of Current/Special Interest" },
  { code: "BSCS-624", name: "Project (FYP)" },
  { code: "BSCS-625", name: "VLSI Design Techniques" },
];